package com.ureca.day4;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;

class MyException extends Exception {
	public MyException() {
		this("MyException");
	}

	public MyException(String message) {
		super(message);
		
	}
	
}

/**
 * throwable 애들 실행되는 순간, 그 뒤에 코드 뭐가 있던 간, 그냥 모든 게 Stop된다.
 * 
 */


public class ExceptionTest {

	public static void main(String[] args) throws MyException {
		// 자바 코테에서는 그냥 throws Exception으로 모든 예외 처리를 그냥 한번에 하는 거야.
		System.out.println("Start");
		
		/**
		 * 1. 로컬 변수는 초기화 해야한다 => 안하면 컴파일 에러
		 * 2. 변수가 null 이고 출력하면 => NullPointerException
		 */
		
		try {
			String s=null;
//			System.out.println(s.length());		// NullPointerException
//			System.in.read();				// IOException
			
//			int i = 10 / 0;
//			if (true) return;
//			System.out.println("Try문이라 출력");
			
			throw new MyException();       			// catch문으로 전달하는 것?
			// throw는 날 선언한 곳으로 그냥 다시 보내는 것
			// 그러면 try-catch로 할지, throws를 선언해둔 곳으로 처리할지 어떻게 할건가?
			/**
			 * 어느 게 나은지, throws로 위임시킨다. 그냥 예외가 발생했다고 계속 알림을 던져서 throws를 넘겨.
			 * 최종적으로 main이 받아서, 처리한다. main이 최후의 보루 느낌
			 * main에서 try-catch로 이제 잘 설계해서 예외들을 받아서 처리하는 거얌
			 */
			
			
		} catch (NullPointerException e) {
			System.out.println("NullPointerException" + e.getMessage());
		} catch (ArithmeticException e) {					// ArithmeticException 발생한 경우
			System.out.println("ArithmeticException" + e.getMessage());
		} 
//		catch (RuntimeException e) {					// RuntimeException 발생한 경우
//			System.out.println("RuntimeException" + e.getMessage());
//		} catch (Exception e) {					// Exception 발생한 경우
//			System.out.println("Exception" + e.getMessage());
//		} catch(Throwable e) {					// Throwable 발생한 경우
//			System.out.println("Throwable" + e.getMessage());
//		} 
		finally {								// finally는 앞에서 return을 해도 실행이 된다. System.exit(0)만 finally의 실행을 막는다.
			System.out.println("finally");
		}
		
		System.out.println("End");
		
		/**
		 *  FileInputStream 생성 및 예외 처리 방법
		 */
		/*
		 * FileInputStream fis = null; try { fis = new FileInputStream("res/input.txt");
		 * 
		 * } catch (FileNotFoundException e) {
		 * 
		 * } finally { try { if (fis != null) fis.close(); // nullpointer 예외 방지 } catch
		 * (IOException e) { // TODO Auto-generated catch block e.printStackTrace(); } }
		 */


		
		try (FileInputStream fis = new FileInputStream("res/input.txt")) {  // 이렇게 선언한다면 위에 긴 코드랑 동일한 거야
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		
		
		
		
		
		
	}

}
